---
#
# Ansible managed
#
repository:
  description: Install and configure Etherpad on your system.
  homepage: https://robertdebock.nl/
  topics: etherpad, development, ansible, molecule, tox, playbook
