---
roles:
  - name: robertdebock.bootstrap
  - name: robertdebock.core_dependencies
  - name: robertdebock.epel
  - name: robertdebock.npm
  - name: robertdebock.service
collections:
  - name: community.general
